[phases.setup]
nixPkgs = [
    "python310",
    "gcc",
    "libgl1",
    "glib"
]

[phases.install]
cmds = [
    "python -m pip install --upgrade pip",
    "python -m pip install numpy==1.21.0 pillow>=9.0.0",
    "python -m pip install torch==2.0.1+cpu torchvision==0.15.2+cpu --find-links https://download.pytorch.org/whl/torch_stable.html",
    "python -m pip install -r requirements.txt"
]

[start]
cmd = "gunicorn app:app --bind=0.0.0.0:$PORT --workers=2 --timeout=120"
