[phases.setup]
nixPkgs = ['python39', 'gcc', 'pkg-config', 'python39Packages.pip']

[phases.install]
cmds = [
    'python -m ensurepip --upgrade',
    'python -m pip install --upgrade pip',
    'pip install -r requirements.txt'
]

[start]
cmd = 'gunicorn app:app --bind=0.0.0.0:$PORT'
