[phases.setup]
nixPkgs = [
    'python39',
    'python39Packages.pip',
    'python39Packages.flask',
    'python39Packages.numpy',
    'python39Packages.pillow',
    'python39Packages.opencv4',
    'python39Packages.torch',
    'python39Packages.torchvision',
    'python39Packages.gunicorn',
    'python39Packages.python-dotenv',
    'python39Packages.flask-cors',
    'gcc',
    'pkg-config'
]

[start]
cmd = 'gunicorn app:app --bind=0.0.0.0:$PORT'
