[phases.setup]
commands = [
  "apt-get update",
  "apt-get install -y python3 python3-pip"
]

[phases.install]
commands = ["pip3 install -r requirements.txt"]

[phases.start]
commands = ["python3 app.py"] # Remplacez `app.py` par le nom de votre fichier principal si nécessaire
